### ISSUE TITLE
**Make Announcement 📣**

### ISSUE THREAD

**Issue by bluenotgreen** [swarm-press/swarm-ath-main#6]
We'll make the announcement in two parts:
- First, we'll promote the community events. We'll share the link to the ATH page and encourage people to visit the website, scan the QR code, and subscribe to the Google Calendar.
- Second, we'll promote the breakout rooms. We'll share the link to the ATH page and encourage people to visit the website, scan the QR code, and sign up for the breakout rooms they're interested in.

**Comment by sirwolcott** [comment]
Announcements have started, been soft launching asking for people to input community events to our break out room sign up form. 2 weeks of that announcement. This past week I created the gCal link and added it to the slides. 

So far, Jadjei is the only one to test the sign up form. He input an event that occurred 2 days from his input. This is too short of a turnaround time for myself or @cauechianca to manually update the calendar. Automations are needed.

**Comment by bluenotgreen** [comment]
In [this Issue](https://github.com/swarm-press/swarm-ath-main/issues/9) we've got the basic ideation for automating. 😊

**Comment by bluenotgreen** [comment]
>  First test:
> 
> https://swarm-press.github.io/swarm-ath-slides/
> Went ONLINE on May, 31st.
> Link to the recording:
> https://www.youtube.com/watch?v=CaKQAhnOKbE
>
>See:  https://github.com/swarm-press/swarm-ath-main/issues/8#issuecomment-1570829290
